name: Teeks
favicon: null
layout_spectrum: 0.3764
typography_spectrum: 0.48554
title: Teeks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#be8bb4'
    - '#2f6291'
    - '#222e6a'
    - '#932c71'
    - '#af5588'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
